### ISSUE TITLE
Nickname Change Crash

### ISSUE THREAD

**Issue by emeryp15** [Ellpeck/FoeFrenzyIssues#2]
FF on Steam crashes on Linux when trying to change nickname
Running on Ubuntu 16.04.6 LTS, latest Steam
Latest FF (0.2.4.5)

# To replicate:
1. Open the game.
1. Select Play Online.
1. Select Online Options.
1. Type anything.

Other options work fine, only changing name causes this.

**Comment by Ellpeck** [comment]
Crash Report?

**Comment by emeryp15** [comment]
https://gist.github.com/emeryp15/07f31abe979aa213673eba7ff4ed98db
