### ISSUE TITLE
(Steam) Unfocusing & refocusing the window opens the steam "invite friends" gui in host screen

### ISSUE THREAD

**Issue by PolarizedIons** [Ellpeck/FoeFrenzyIssues#3]
**Describe the issue**
On the steam version of the game, when I am in the hosting screen, and I unfocus & refocus the game window, the steam "invite friends" gui shows up

**To Reproduce**
Steps to reproduce:
0. Use the steam version
1. Go into hosting screen (Play Online -> Host)
2. Click outside the window
3. Click back inside the window
4. Notice the steam "invite friends" gui pop up

**Expected behavior**
The steam "invite friends" to only pop up when I press the assigned keys.

**Crash Report**
None

**Screenshots**
None

**Game Info**
 - Operating System: Arch Linux
 - Game Version: 0.2.4.6 (Steam)

**Comment by Ellpeck** [comment]
This was happening due to #6 where the shoulder button would get stuck, so this is actually not the issue you're describing.
