### ISSUE TITLE
Afrikaans translation gets cut off

### ISSUE THREAD

**Issue by PolarizedIons** [Ellpeck/FoeFrenzyIssues#4]
**Describe the issue**
The Afrikaans translation for the two player keyboard description gets cut off

**To Reproduce**
Steps to reproduce:
1. Switch to Afrikaans
2. Open Options

**Expected behavior**
For the text to wrap around to a new line

**Crash Report**
none

**Screenshots**
![image](https://user-images.githubusercontent.com/4587682/68969628-17bb8e80-07ee-11ea-828a-5e5438cbcc07.png)

**Game Info**
 - Operating System: Arch Linux
 - Game Version: 0.2.4.6 (steam)

**Comment by PolarizedIons** [comment]
On the play manu aswell it seems
![image](https://user-images.githubusercontent.com/4587682/68969696-489bc380-07ee-11ea-8733-00cc6cda03bf.png)

**Comment by Ellpeck** [comment]
Isn't it possible for you to make the line shorter? I'd rather not have it wrap, especially in the options menu, as it'll look even more cramped than it already does.
