### ISSUE TITLE
Steam joining desync

### ISSUE THREAD

**Issue by PolarizedIons** [Ellpeck/FoeFrenzyIssues#5]
**Describe the issue**
I accidentally joined twice (controller & keyboard), I exited hosting and restarted it, Raqbit joined me again, and he saw two of my players still, but I joined only once this time.

**To Reproduce**
Steps to reproduce:
Not really easy to reproduce it seems

**Expected behavior**
There to only be one player

**Crash Report**
none

**Screenshots**
![image](https://user-images.githubusercontent.com/4587682/68970085-2a829300-07ef-11ea-986c-01a150077b65.png)

**Game Info**
 - Operating System: Arch Linux
 - Game Version: 0.2.4.6

**Comment by Raqbit** [comment]
My view
![Screenshot from 2019-11-15 20-27-08](https://user-images.githubusercontent.com/11144180/68970167-f4411580-07e6-11ea-9e35-7bd26ad58cdb.png)

**Comment by Ellpeck** [comment]
bleh
