### ISSUE TITLE
Facing stuck

### ISSUE THREAD

**Issue by Raqbit** [Ellpeck/FoeFrenzyIssues#6]
**Describe the issue**
The facing of one of the characters got stuck in a single direction on both ends, even though the player was moving.

The issue persisted across multiple rounds and even after rejoining the multiplayer game.

**To Reproduce**
Good luck

**Expected behavior**
The facing should update with the moving direction.

**Screencast**
https://youtu.be/PAoRJV1F7xM

**Game Info**
 - Operating System: Manjaro Linux (Rolling Release)
 - Game Version: 0.2.4.6

**Comment by Ellpeck** [comment]
Are you.. holding the strafe key? 🤔

**Comment by Raqbit** [comment]
I'm using a controller and moving the left thumb stick. Has happend to both me and @PolarizedIons (he is also using a controller)

**Comment by Raqbit** [comment]
It seems like the `L1` button is getting stuck when you press it to open the invite screen. Re-pressing it fixes the button getting stuck
