### ISSUE TITLE
Bomb throwing desync

### ISSUE THREAD

**Issue by Raqbit** [Ellpeck/FoeFrenzyIssues#8]
**Describe the issue**
I threw a bomb while walking out of the water but it the bomb vanished. @PolarizedIons could see the bomb explode and still sees the damage but I don't see anything.

**To Reproduce**
Could not reproduce.

**Expected behavior**
Both clients should show the bomb explode & show the damage it creates.

**Screenshots**

My point of view:

![Screenshot from 2019-11-15 21-21-29](https://user-images.githubusercontent.com/11144180/68973266-19855200-07ee-11ea-9582-f48d0af7f2ce.png)

**Game Info**
 - Operating System: Manjaro Linux (Rolling Release)
 - Game Version: 0.2.4.6

**Comment by PolarizedIons** [comment]
![image](https://user-images.githubusercontent.com/4587682/68973421-eabfa980-07f6-11ea-8a3b-04cf3df29d12.png)

**Comment by Ellpeck** [comment]
seriously this game's netcode is so badly made
